### PR TITLE
<Implement API of framework #6>: Defined next API:

### LINKED ISSUE #6: Implement API of framework
The following api should be defined
- BeanDefinition
- BeanFactory
- PackageScanner
- ApplicationContext
- Exceptions

### PR DESCRIPTION
**Pull request by AlexandrLavrinenko**
- ApplicationContext
- AnnotationApplicationContext
- ApplicationContextExceptions
- BeanDefinition
- BeanFactory
- BeanPostProcessor
- BeansException
- DefaultBeanFactory
- PackageScanner

### CODE REVIEW

**Review by DimaGalchenko — APPROVED** [review]

File: src/main/java/com/codeus/winter/config/BeanDefinition.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
+package com.codeus.winter.config;
+
+import javax.annotation.Nullable;
+
+public interface BeanDefinition {
+    /**
+     * Scope identifier for the standard singleton scope: {@value}.
+     */
+    String SCOPE_SINGLETON = "SCOPE_SINGLETON";
```
Comment (khshanovskyi) [inline src/main/java/com/codeus/winter/config/BeanDefinition.java]: I suppose it should be enum with name Scope and constants SINGLETON and PROTOTYPE

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+
+    @Nullable
+    @Override
+    public Object getBean(Class<Object> requiredType) throws BeansException {
+        return singletonBeans.entrySet().stream()
+                .map(Map.Entry::getValue)
+                .filter(requiredType::isInstance)
+                .findFirst()
+                .map(requiredType::cast)
+                .orElseThrow(() -> new BeansException("Bean not found for type: " + requiredType.getName()));
```
Comment (khshanovskyi) [inline src/main/java/com/codeus/winter/config/DefaultBeanFactory.java]: we need to create for each specified case some specified exception
not found -> BeanNotFoundException
2+ realizations -> NotUniqueBeanDefinitionException

**Review by khshanovskyi — APPROVED** [review]

File: src/main/java/com/codeus/winter/config/BeanDefinition.java (hunk 1 above)
Comment (DimaGalchenko) [reply src/main/java/com/codeus/winter/config/BeanDefinition.java]: Fun fact: in Spring, these constants are also in this BeanDefinition class:
Screenshot 2024-11-05 at 09 06 35
But I agree with you, Enum would be a more convenient place.

File: src/main/java/com/codeus/winter/exception/BeansException.java [hunk 3]
```diff
@@ -0,0 +1,13 @@
+package com.codeus.winter.exception;
+
+import javax.annotation.Nullable;
```
Comment (vromantsev) [inline src/main/java/com/codeus/winter/exception/BeansException.java:3]: I'd suggest using `jakarta.*` packages/classes instead of `javax.*`

File: src/main/java/com/codeus/winter/config/BeanDefinition.java (hunk 1 above)
Comment (AlexandrLavrinenko) [reply src/main/java/com/codeus/winter/config/BeanDefinition.java]: I fixed it with Enum

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java (hunk 2 above)
Comment (AlexandrLavrinenko) [reply src/main/java/com/codeus/winter/config/DefaultBeanFactory.java]: I created an extra Exception - NotUniqueBeanDefinitionException and renamed BeansException to BeanNotFoundException.
After that, I fixed the logic in the methods according to the comment.

File: src/main/java/com/codeus/winter/exception/BeansException.java (hunk 3 above)
Comment (AlexandrLavrinenko) [reply src/main/java/com/codeus/winter/exception/BeansException.java:3]: The dependency was updated.

**Comment by AlexandrLavrinenko** [comment]
I fixed all the comments, re-review task again, please.

**Review by AndriyPavlyuk — APPROVED** [review]
