### PR TITLE
47 autowiring constructor

### LINKED ISSUE #47: Implement @Autowired Annotation Support in BeanFactory
**Summary**

Add support for the @Autowired annotation in the DefaultBeanFactory class to enable automatic dependency injection constructor parameters.

**Description**

Currently, the DefaultBeanFactory does not support constructor-based dependency injection using annotations. Implement support for the @Autowired annotation to automatically resolve and inject constructor parameters based on the available beans.

Implementation details:
- Check for constructors annotated with @Autowired and use the annotated constructor for instantiation.
- Resolve all constructor parameters from the available beans.
- Throw an exception if dependencies cannot be resolved.

### PR DESCRIPTION
**Pull request by SergiiKravchuk**
Changes:
- added logic to find a bean's autowired constructor and use it to instantiate the bean;
- added logic to find all candidate beans for autowiring;
- an overhaul of the `DefaultBeanFactory` to support dynamic bean instantiation;
- [QOL] covered new logic with Java Docs;
- added TODOs that should be resolved in future tickets.

### CODE REVIEW

**Comment by SergiiKravchuk** [comment]
Temporarily targeting another feature branch for correct changes display.

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java [hunk 1]
```diff
@@ -175,147 +182,289 @@ private <T> void checkBeanClassUniqueness(@Nonnull final Class<T> beanClass) {
...
-            }
+    /**
+     * Retrieves an existing singleton bean by bean's name and definition.
+     * Can create a singleton bean if it is not created yet.
+     *
+     * @param beanName       a name of a singleton bean to retrieve or create.
+     * @param beanDefinition a definition of a singleton bean to retrieve or create.
+     * @return a singleton bean.
+     */
+    private Object getSingleton(String beanName, BeanDefinition beanDefinition) {
```
Comment (DimaGalchenko) [inline src/main/java/com/codeus/winter/config/DefaultBeanFactory.java:227]: Minor: I would suggest changing the name of this method, as it says it gets a bean, but it can actually get or create

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java [hunk 2]
```diff
@@ -175,147 +182,289 @@ private <T> void checkBeanClassUniqueness(@Nonnull final Class<T> beanClass) {
...
-    }
 
-    private Object resolveConstructor(Class<?> beanClass) {
-        Constructor<?>[] constructors = beanClass.getConstructors();
+        if (explicitAutowiringConstructor != null)
+            return explicitAutowiringConstructor;
+        else if (candidates.size() == 1 && !hasExplicitDefaultConstructor)
+            return candidates.getFirst();
+        else if (candidates.size() == 2 && hasExplicitDefaultConstructor)
+            return candidates.stream().filter(constructor -> constructor.getParameterCount() > 0).findAny().orElse(null);
```
Comment (DimaGalchenko) [inline src/main/java/com/codeus/winter/config/DefaultBeanFactory.java]: Why do we prefer a constructor with parameters >0 to a constructor with zero parameters?

**Review by DimaGalchenko — APPROVED** [review]
Awesome changes. Thanks for refactoring so many places. Leave a minor comment and question

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java (hunk 1 above)
Comment (SergiiKravchuk) [reply src/main/java/com/codeus/winter/config/DefaultBeanFactory.java:227]: Yeah, but all `getBean` methods from `DefaultBeanFactory`'s API either retrieve and create a bean. The only method that is out of the format - is `getOrCreateBean`, I named it to clearly differentiate between the API and private version.

Anyway, do you have any suggestions regarding re-naming?

I believe, `getOrCreateBean` can be renamed to `getBean`, so there won't be any differences in the naming format , and `get*` naming implicitly would mean that the method can retrieve and create. As the result,  `getSingleton` would sound right as well😄.

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java (hunk 2 above)
Comment (SergiiKravchuk) [reply src/main/java/com/codeus/winter/config/DefaultBeanFactory.java]: In the scope of this method, we are only interested in finding an autowiring constructor, the default one (constructor with zero parameters) is not an autowiring constructor.

Techically, in the current codebase, returning a constructor with zero parameters as an autowiring constructor works. But it works now, I believe we should not add the responsibility of handing a constructor with zero parameters to the autowiring constructor processing flow. So this is why there is a separate flow to instantiate a bean using the default constructor.

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java (hunk 1 above)
Comment (DimaGalchenko) [reply src/main/java/com/codeus/winter/config/DefaultBeanFactory.java:227]: ok, let's leave getSingleton

File: src/main/java/com/codeus/winter/config/DefaultBeanFactory.java (hunk 2 above)
Comment (DimaGalchenko) [reply src/main/java/com/codeus/winter/config/DefaultBeanFactory.java]: ok, thanks for answering

**Review by khshanovskyi — APPROVED** [review]
I like how the code is written

**Review by Mitos35 — APPROVED** [review]

File: src/main/java/com/codeus/winter/config/AbstractAutowireCapableBeanFactory.java [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Optional;
+
+/**
+ * An extension of {@link BeanFactory} that provides extra logic for bean resolving and autowiring.
+ */
+public abstract class AbstractAutowireCapableBeanFactory implements BeanFactory {
+    private final ConstructorResolver constructorResolver;
+
```
Comment (AndriyPavlyuk) [inline src/main/java/com/codeus/winter/config/AbstractAutowireCapableBeanFactory.java:18]: I don't see any other classes that extend AbstractAutowireCapableBeanFactory, so it shouldn't be an abstract class. Also I don't see other possibilities in the future to use this class for other implementation since it is a core class of framework. 
Looks weird that ConstructorResolver can deal with different implementations of BeanFactory. There is only one main flow for this framework.
